# auto_test.yml
name: Auto Test
on:
push:
branches: ["main"]
pull request:
branches:
["main"]
jobs:
test:
runs - on:
euleros -2.10.1
steps:
- name: download
run: wget "https://cangjie-lang.cn/v1/files/auth/downLoad?nsId=142267&fileName=Cangjie-0.53.13-linux_x64.tar.gzaobjectKey=6719f
- uses: checkout-action@o.o.1
- name: test run:
• cangjie/envsetup. sh && cjc -- version && cd repo_workspace && cjpm update && cjpm build && cjpm test
